defaults:
  - _self_
  - datasets: shapenet.yaml
  - override hydra/hydra_logging: disabled   # disable hydra logging
  - override hydra/job_logging: disabled   # disable job logging

hydra:
  output_subdir: null  # disable creating .hydra directory
  run:
    dir: .  # disable output directory created by hydra
  job:
    chdir: false  # disable changing working directory

usr_config: null  # e.g. project_root/configs/user_configs/user_config1.yaml

train:
  epochs: 100
  lr: 1e-3
  optimizer: adam  # aam or sgd
  which_gpu: [0, 1]  # only valid when device is gpu
  pin_memory: true  # pin memory in RAM
  validation_freq: 10  # frequency in epoch(s) to validate the model
  dataloader:
    batch_size: 16
    shuffle: true
    num_workers: 16  # the number of subprocess to load data
    prefetch: 16  # samples to be prefetched. e.g. 64 means 64*num_workers samples to be prefetched

edgeconv_block:
  K: [32, 32, 32]
  xyz_or_feature: ['feature', 'feature', 'feature']  # select K neighbors according to xyz or current feature
  feature_or_diff: ['diff', 'diff', 'diff']  # use the features of K neighbors or use the difference between the given point and its K neighbors as cross attention input
  conv1_channel_in: [6, 128, 128]
  conv1_channel_out: [64, 64, 64]
  conv2_channel_in: [64, 64, 64]
  conv2_channel_out: [64, 64, 64]

point2neighbor_block:
  enable: true  # if false, edgeconv block will be used
  use_embedding: true
  embedding_channels_in: 3
  embedding_channels_out: 64
  point2neighbor:
    K: [32, 32, 32]
    xyz_or_feature: ['feature', 'feature', 'feature']  # select K neighbors according to xyz or current feature
    feature_or_diff: ['diff', 'diff', 'diff']  # use the features of K neighbors or use the difference between the given point and its K neighbors as cross attention input
    qkv_channels: [64, 64, 64]
    ff_conv1_channels_in: [64, 64, 64]
    ff_conv1_channels_out: [128, 128, 128]
    ff_conv2_channels_in: [128, 128, 128]
    ff_conv2_channels_out: [64, 64, 64]

conv_block:
  channels_in: [192]
  channels_out: [1024]

point2point_block:
  enable: false  # if false, conv block will be used
  use_embedding: true
  embedding_channels_in: 192
  embedding_channels_out: 1024
  point2point:
    qkv_channels: [1024]
    ff_conv1_channels_in: [1024]
    ff_conv1_channels_out: [512]
    ff_conv2_channels_in: [512]
    ff_conv2_channels_out: [1024]

point2neighbor_multi_scale:
  enable: true

point2patch:
  enable: true